"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { KeyRound, Webhook, XCircle } from "lucide-react";
import { api, type APIKey, type WebhookToken } from "@/lib/api";
import { AppPageHeader } from "@/components/ui/app-page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DataList, Panel } from "@/components/ui/dashboard";
import { ConfirmDialog } from "@/components/ui/dialogs/confirm-dialog";
import { SecretRevealDialog } from "@/components/ui/dialogs/secret-reveal-dialog";
import { ErrorState } from "@/components/ui/feedback/error-state";
import { LoadingState } from "@/components/ui/feedback/loading-state";
import { CheckboxField, DateField, FormCard, FormCardContent, FormCardDescription, FormCardFooter, FormCardHeader, FormCardTitle, FormField, SelectField, SubmitAction, TextField } from "@/components/ui/form";

type Credential = APIKey | WebhookToken;
type Target = { kind: "api"; item: APIKey } | { kind: "webhook"; item: WebhookToken } | null;
type DataRows = Parameters<typeof DataList>[0]["rows"];
const dateFormatter = new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" });

function formatDate(value: string | null | undefined) { if (!value) return "Never"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : dateFormatter.format(date); }
function statusOf(item: Pick<Credential, "revoked_at" | "expires_at">) { return item.revoked_at ? "Revoked" : item.expires_at && new Date(item.expires_at).getTime() <= Date.now() ? "Expired" : "Active"; }
function StatusBadge({ status }: { status: ReturnType<typeof statusOf> }) { return <Badge variant={status === "Active" ? "success" : status === "Expired" ? "warning" : "danger"}>{status}</Badge>; }
function latest<T extends { created_at: string }>(items: T[]) { return [...items].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()); }

function Metadata({ prefix, detail, item }: { prefix: string; detail: string; item: Credential }) {
  return <div className="space-y-1"><p><span className="font-mono text-[#3D3935]">{prefix}</span> · {detail}</p><p>Created {formatDate(item.created_at)} · Last used {formatDate(item.last_used_at)}{item.expires_at ? ` · Expires ${formatDate(item.expires_at)}` : ""}{item.revoked_at ? ` · Revoked ${formatDate(item.revoked_at)}` : ""}</p></div>;
}

function CredentialList({ title, description, rows, loading, error, onRetry }: { title: string; description: string; rows: DataRows; loading: boolean; error: string; onRetry: () => void }) {
  return <Panel><div className="mb-4"><h2 className="text-sm font-semibold">{title}</h2><p className="mt-1 text-xs text-[#706A63]">{description}</p></div>{loading ? <LoadingState label={`Loading ${title.toLowerCase()}…`} /> : error ? <ErrorState message={error} onRetry={onRetry} /> : <DataList rows={rows} />}</Panel>;
}

export default function IntegrationsPage() {
  const [apiKeys, setApiKeys] = useState<APIKey[]>([]); const [webhooks, setWebhooks] = useState<WebhookToken[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [apiName, setApiName] = useState(""); const [read, setRead] = useState(true); const [write, setWrite] = useState(false); const [apiExpiry, setApiExpiry] = useState(""); const [apiBusy, setApiBusy] = useState(false);
  const [webhookName, setWebhookName] = useState(""); const [source, setSource] = useState("ios"); const [webhookExpiry, setWebhookExpiry] = useState(""); const [webhookBusy, setWebhookBusy] = useState(false);
  const [secretValue, setSecretValue] = useState(""); const [secretTitle, setSecretTitle] = useState("Credential created"); const [target, setTarget] = useState<Target>(null); const [revoking, setRevoking] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [keys, tokens] = await Promise.all([api.apiKeys({ include_revoked: true }), api.webhookTokens({ include_revoked: true })]); setApiKeys(latest(keys)); setWebhooks(latest(tokens)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load Vault credentials."); } finally { setLoading(false); } }, []);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const liveKeys = useMemo(() => apiKeys.filter((item) => !item.revoked_at), [apiKeys]); const liveWebhooks = useMemo(() => webhooks.filter((item) => !item.revoked_at), [webhooks]);
  const revoked = useMemo(() => latest([...apiKeys.filter((item) => item.revoked_at).map((item) => ({ kind: "API key", item, created_at: item.created_at })), ...webhooks.filter((item) => item.revoked_at).map((item) => ({ kind: "Webhook", item, created_at: item.created_at }))]), [apiKeys, webhooks]);
  async function createKey(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!apiName.trim() || (!read && !write)) return; setApiBusy(true); setNotice(""); try { const created = await api.createAPIKey({ name: apiName.trim(), scopes: [read && "transactions:read", write && "transactions:write"].filter((scope): scope is string => Boolean(scope)), ...(apiExpiry ? { expires_at: apiExpiry } : {}) }); setApiName(""); setRead(true); setWrite(false); setApiExpiry(""); await load(); if (created.token) { setSecretTitle("API key created — copy it now"); setSecretValue(created.token); } else setNotice("API key created, but its secret was not returned."); } catch (caught) { setNotice(caught instanceof Error ? caught.message : "Could not create the API key."); } finally { setApiBusy(false); } }
  async function createWebhook(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!webhookName.trim()) return; setWebhookBusy(true); setNotice(""); try { const created = await api.createWebhookToken({ name: webhookName.trim(), source, ...(webhookExpiry ? { expires_at: webhookExpiry } : {}) }); setWebhookName(""); setSource("ios"); setWebhookExpiry(""); await load(); if (created.token) { setSecretTitle("Webhook secret created — copy it now"); setSecretValue(created.token); } else setNotice("Webhook secret created, but its secret was not returned."); } catch (caught) { setNotice(caught instanceof Error ? caught.message : "Could not create the webhook secret."); } finally { setWebhookBusy(false); } }
  async function revoke() { if (!target) return; setRevoking(true); setNotice(""); try { if (target.kind === "api") await api.revokeAPIKey(target.item.id); else await api.revokeWebhookToken(target.item.id); setTarget(null); await load(); } catch (caught) { setNotice(caught instanceof Error ? caught.message : "Could not revoke this credential."); } finally { setRevoking(false); } }
  const keyRows: DataRows = liveKeys.map((item) => ({ id: item.id, title: <div className="flex flex-wrap items-center gap-2"><span>{item.name}</span><StatusBadge status={statusOf(item)} /></div>, meta: <Metadata prefix={item.key_prefix} detail={item.scopes.join(", ")} item={item} />, action: <Button variant="ghost" size="sm" className="text-red-700 hover:text-red-800" onClick={() => setTarget({ kind: "api", item })}>Revoke</Button> }));
  const webhookRows: DataRows = liveWebhooks.map((item) => ({ id: item.id, title: <div className="flex flex-wrap items-center gap-2"><span>{item.name}</span><StatusBadge status={statusOf(item)} /></div>, meta: <Metadata prefix={item.token_prefix} detail={`Source: ${item.source}`} item={item} />, action: <Button variant="ghost" size="sm" className="text-red-700 hover:text-red-800" onClick={() => setTarget({ kind: "webhook", item })}>Revoke</Button> }));
  const revokedRows: DataRows = revoked.map(({ kind, item }) => ({ id: `${kind}-${item.id}`, title: <div className="flex flex-wrap items-center gap-2"><span>{item.name}</span><StatusBadge status="Revoked" /></div>, meta: <Metadata prefix={"key_prefix" in item ? item.key_prefix : item.token_prefix} detail={"scopes" in item ? `${kind} · ${item.scopes.join(", ")}` : `${kind} · Source: ${item.source}`} item={item} /> }));
  const minDate = new Date().toISOString().slice(0, 10);
  return <div className="min-h-screen p-6"><AppPageHeader title="Vault" eyebrow="Integrations" description="Issue and revoke narrowly scoped credentials for trusted finance workflows." />
    {notice ? <p role="status" className="mb-5 rounded-lg border border-[#D8D1C8] bg-[#FFFEFC] px-4 py-3 text-sm text-[#514B44]">{notice}</p> : null}
    <div className="grid gap-6 xl:grid-cols-2">
      <FormCard variant="sensitive"><form onSubmit={createKey}><FormCardHeader><div><FormCardTitle className="flex items-center gap-2"><KeyRound className="size-4" />API key</FormCardTitle><FormCardDescription>Use scopes to limit what an integration can do.</FormCardDescription></div></FormCardHeader><FormCardContent className="space-y-4"><FormField label="Name" required><TextField value={apiName} onChange={(event) => setApiName(event.target.value)} placeholder="e.g. reconciliation service" /></FormField><FormField label="Quick preset"><SelectField value={read && write ? "read-write" : "read"} onChange={(event) => { const both = event.target.value === "read-write"; setRead(true); setWrite(both); }}><option value="read">Read only (transactions:read)</option><option value="read-write">Read &amp; write (transactions:read, transactions:write)</option></SelectField></FormField><fieldset className="space-y-2"><legend className="text-xs font-semibold text-[#3D3935]">Granular scopes</legend><label className="flex items-center gap-2 text-sm"><CheckboxField checked={read} onChange={(event) => setRead(event.target.checked)} />transactions:read</label><label className="flex items-center gap-2 text-sm"><CheckboxField checked={write} onChange={(event) => setWrite(event.target.checked)} />transactions:write</label></fieldset><FormField label="Expiry" hint="Optional; expires at the start of the selected local date."><DateField value={apiExpiry} min={minDate} onChange={(event) => setApiExpiry(event.target.value)} /></FormField></FormCardContent><FormCardFooter><SubmitAction isSubmitting={apiBusy} label="Create API key" busyLabel="Creating…" disabled={!apiName.trim() || (!read && !write)} /></FormCardFooter></form></FormCard>
      <FormCard variant="sensitive"><form onSubmit={createWebhook}><FormCardHeader><div><FormCardTitle className="flex items-center gap-2"><Webhook className="size-4" />Webhook secret</FormCardTitle><FormCardDescription>Authorize one incoming source without exposing account access.</FormCardDescription></div></FormCardHeader><FormCardContent className="space-y-4"><FormField label="Name" required><TextField value={webhookName} onChange={(event) => setWebhookName(event.target.value)} placeholder="e.g. iOS shortcut" /></FormField><FormField label="Source"><SelectField value={source} onChange={(event) => setSource(event.target.value)}><option value="ios">iOS</option><option value="cronjob">Cronjob</option><option value="api">API</option></SelectField></FormField><FormField label="Expiry" hint="Optional; expires at the start of the selected local date."><DateField value={webhookExpiry} min={minDate} onChange={(event) => setWebhookExpiry(event.target.value)} /></FormField></FormCardContent><FormCardFooter><SubmitAction isSubmitting={webhookBusy} label="Create webhook secret" busyLabel="Creating…" disabled={!webhookName.trim()} /></FormCardFooter></form></FormCard>
    </div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><CredentialList title="API keys" description="Active and expired keys. Scopes are metadata only; the key itself is never shown again." rows={keyRows} loading={loading} error={error} onRetry={load} /><CredentialList title="Webhook secrets" description="Active and expired inbound secrets." rows={webhookRows} loading={loading} error={error} onRetry={load} /></div>
    <Panel className="mt-6"><div className="mb-4 flex items-center gap-2"><XCircle className="size-4 text-[#A54B36]" /><div><h2 className="text-sm font-semibold">Revoked history</h2><p className="text-xs text-[#706A63]">Revoked credentials are retained as an audit trail.</p></div></div>{loading ? <LoadingState label="Loading revoked history…" /> : error ? <ErrorState message={error} onRetry={load} /> : <DataList rows={revokedRows} />}</Panel>
    <SecretRevealDialog secretValue={secretValue} title={secretTitle} description="This value is shown once. Copy it before closing this window." open={Boolean(secretValue)} onOpenChange={(open) => { if (!open) setSecretValue(""); }} />
    <ConfirmDialog open={Boolean(target)} onOpenChange={(open) => { if (!open && !revoking) setTarget(null); }} title="Revoke credential?" description={`This immediately disables ${target?.item.name ?? "this credential"}. Hold the revoke button for two seconds to confirm.`} variant="danger" confirmLabel="Hold to revoke" isConfirming={revoking} onConfirm={() => void revoke()} />
  </div>;
}
